### ISSUE TITLE
Mockito cannot mock this class: class org.openqa.selenium.chrome.ChromeDriver.

### ISSUE THREAD

**Issue by sunnysachdeva99** [sudharsan-selvaraj/wow-xhr#1]
HI,

I want to try this lib to intercept a response, however, I am getting an exception .

org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class org.openqa.selenium.chrome.ChromeDriver.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.

Java               : 11
JVM vendor name    : Oracle Corporation
JVM vendor version : 11.0.10+8-LTS-162
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 11.0.10+8-LTS-162
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 10.16

> Underlying exception : java.lang.IllegalArgumentException: Could not create type
> 
> 	at io.github.sudharsan_selvaraj.SpyDriver.<init>(SpyDriver.java:20)
> 	at io.github.sudharsan_selvaraj.SpyDriver.<init>(SpyDriver.java:13)
> 	at io.github.sudharsan_selvaraj.wowxhr.WowXHR.<init>(WowXHR.java:20)
> 	at SeleniumMocking.MockTags.beforeSuite(MockTags.java:20)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
> 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
> 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
> 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
> 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
> 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
> 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
> 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
> 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
> 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
> 	at org.testng.TestNG.runSuites(TestNG.java:1049)
> 	at org.testng.TestNG.run(TestNG.java:1017)
> 	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
> 	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
> Caused by: java.lang.IllegalArgumentException: Could not create type
> 	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:139)
> 	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:344)
> 	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:159)
> 	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:353)
> 	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
> 	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:71)
> 	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:42)
> 	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:25)
> 	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
> 	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:63)
> 	at org.mockito.Mockito.mock(Mockito.java:1908)
> 	at org.mockito.Mockito.mock(Mockito.java:1880)
> 	... 23 more
> Caused by: java.lang.NoSuchMethodError: net.bytebuddy.dynamic.loading.MultipleParentClassLoader$Builder.appendMostSpecific(Ljava/util/Collection;)Lnet/bytebuddy/dynamic/loading/MultipleParentClassLoader$Builder;
> 	at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:84)
> 	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
> 	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
> 	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:137)
> 	... 34 more

**My code is :-**

```
public class MockTags {

    WebDriver driver;
    WowXHR wowXhr;
    @BeforeSuite
    public void beforeSuite() throws DriverNotSupportedException {
        WebDriverManager.chromedriver().setup();
        wowXhr = new WowXHR(new ChromeDriver());
        driver = wowXhr.getMockDriver();
        driver.navigate().to("https://react-redux.realworld.io/");
    }

    @Test
    public void mockTest() throws InterruptedException {
        driver.findElement(By.linkText("Sign in")).click();
        driver.findElement(By.cssSelector("input[type='email']")).sendKeys("abc@tester.com");
        driver.findElement(By.cssSelector("input[type='password']")).sendKeys("Qwerty@123");
        driver.findElement(By.xpath("//button[@type='submit']")).click();

        Thread.sleep(5000);

        wowXhr.mock().add(
                Mockable.whenGET("/api/tags")
                .respond(
                        Mockable.mockResponse()
                        .withBody("{\"tags\" : [\"mockTag1\", \"mockTag2\"]}")
                )
        );

    }

}
```

**Comment by sudharsan-selvaraj** [comment]
Some dependency issue with Mockito + java 11. Working on the fix now.

**Comment by sudharsan-selvaraj** [comment]
There is a dependency version issue for `net.bytebuddy:byte-buddy` module between `selenium` and `mockito` library.

byte-buddy used by selenium  : `1.8.15`
byte-buddy required by mockito: `1.10.5`

So we need to exclude the dependecy being download by selenium.

**Maven:**
```xml
<dependency>
     <groupId>org.seleniumhq.selenium</groupId>
     <artifactId>selenium-java</artifactId>
      <version>3.141.59</version>
      <exclusions>
          <exclusion>
              <groupId>net.bytebuddy</groupId>
              <artifactId>byte-buddy</artifactId>
           </exclusion>
     </exclusions>
</dependency>
```

**Gradle**
```groovy
implementation (group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '3.141.59') {
        exclude group: 'net.bytebuddy', module: 'byte-buddy'
 }
```

**Comment by sunnysachdeva99** [comment]
issue fixed
